version: '2.0'
services:
  word-dump-service:
    image: scrabbleyourword/word-dump-service:latest
    ports:
      - 9000:8080
  word-processing-service:
    image: scrabbleyourword/word-processing-service:latest
    ports:
      - 9001:8080
  rabbit:
    image: rabbitmq
  rabbit-manager:
    image: rabbitmq:3-management
    ports:
      - 9002:15672
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch1:9200/
    ports:
      - 5601:5601
